### ISSUE TITLE
Pending payment with sandbox ???

### ISSUE THREAD

**Issue by goben2489** [heidelpay/magento-cd-edition#10]
I have test magento-cd-edition with sandbox credit card and order always setting pending payment, have not shortID Receive 

Magento 1.9.2.2
magento-cd-edition : 17.5.17

what happen ?

![image](https://user-images.githubusercontent.com/14970253/27716027-8b0206de-5d65-11e7-96bb-a99754a174cb.png)

**Comment by heidelpay** [comment]
Looks like your shop is not reachable from the Internet. This is necessary  for our payment system. The payment server tries to send the result to http://www.yourshop.de//hcd/response . If you see this URL inside your browser, there is a misbehavior.

**Comment by goben2489** [comment]
yeah, i test module at localhost, module can send request to server but can not receive data. This module can not work at localhost ?

**Comment by heidelpay** [comment]
Thats correct. You can simulate the payment process itself, but the order update and the flow back to the shop can not be tested on a localhost installation. As mentioned above the payment server tries to reach  http(s)://(www.yourshop.de)/hcd/response to tell the shop the result of the transaction.

**Comment by goben2489** [comment]
thank for support, i will test on live server
