### ISSUE TITLE
Can i get REFERENCEID from module ?

### ISSUE THREAD

**Issue by goben2489** [heidelpay/magento-cd-edition#11]
i will test checkout with live server but i dont see REFERENCEID from respone data after checkout success. Because i want use REFERENCEID for payment order recurring, how do it ?

![screen shot 2017-07-03 at 5 33 41 pm](https://user-images.githubusercontent.com/14970253/27789222-e11c5aee-6015-11e7-88c9-73d7023825fb.png)

**Comment by heidelpay** [comment]
Please switch on the recognition first. 

![grafik](https://user-images.githubusercontent.com/9822686/27789634-9665bde2-5fed-11e7-93d5-f5927f9f506b.png)

Then the used payment method will store the payment data or the reference id in the heidelpay_customer table. This depends on the use payment method.

The payment data for direct debit etc. are stored inside the blob. This data are encrypted to protect them against direct access. 

Always use magento models to get the data. https://github.com/heidelpay/magento-cd-edition/blob/master/app/code/community/HeidelpayCD/Edition/Model/Payment/Abstract.php#L634

```

        $customerData = Mage::getModel('hcd/customer')
            ->getCollection()
            ->addFieldToFilter('Customerid', $customerId)
            ->addFieldToFilter('Storeid', $storeId)
            ->addFieldToFilter('Paymentmethode', $paymentCode);

        $customerData->load();
        $data = $customerData->getData();
```

To chage the amount, you can use our php-sdk.  https://dev.heidelpay.de/heidelpay-php-api/

The sdk has a debitOnRegistration method to do so.

If you need more information, feel free to contact us.

**Comment by goben2489** [comment]
i test with sandbox but have error

Err. code	request contains no cc/bank account holder (100.100.400)

![h18](https://user-images.githubusercontent.com/14970253/27857710-ecca2aaa-619c-11e7-879f-27b15d3ecf41.PNG)

i have must test with real card ?

**Comment by heidelpay** [comment]
Looks like you have not made a credit card registration on the checkout page. This could be the case if you use another checkout than the magento once.

![grafik](https://user-images.githubusercontent.com/9822686/27857981-d804e26e-6173-11e7-90e1-df8179f2872f.png)

Credit Card registration should be look like this. /JR

**Comment by goben2489** [comment]
i have use ontstepcheckout ext and it show form below, i can't see yes or no input in iframe request.

![image](https://user-images.githubusercontent.com/14970253/27858277-d5913f7a-619e-11e7-8015-ed6cfc234924.png)

**Comment by heidelpay** [comment]
The problem would be that the javascipt which do the submit of the iframe is only designed for the magento checkout. If you want to use our payment extension and  onestepcheckout extension you have to modify the heidelpay extension on your own. I am sorry but we can not support this. /JR

**Comment by goben2489** [comment]
i test default magento but dont work

![image](https://user-images.githubusercontent.com/14970253/27859206-2f85566c-61a2-11e7-9d56-9145e324c0f2.png)

i think because sandbox test ?

**Comment by heidelpay** [comment]
The registration is send to your system but it response with

URL: http://shave-lab-test.tt-tech.letin/hcd/response/?___store=default
Received response, Status : HTTP/1.0 503 Service Unavailable

Please check that the database tables are there heidelpay_customer and heidelpay_transaction.

**Comment by goben2489** [comment]
yes because i test in localhost, but my mind is a one form show, not like your form result. 
At first payment have not yes/no input ?

**Comment by heidelpay** [comment]
Thats correct the yes/no thing is only there after the first payment and dependent on your setting for recognition only with the same shipping adress.
