### ISSUE TITLE
change cancel and return url in paypal payment

### ISSUE THREAD

**Issue by quannh02** [heidelpay/magento-cd-edition#32]
Hi guys, 
Have any way to change this message to "cancel and return to my site". 
[https://drive.google.com/file/d/1f97HMZHCNZW7vJEILPGe26WIVT6XKOYj/view?usp=sharing](url)
Thanks,
Quan

**Comment by sixer1182** [comment]
Hey @quannh02 ,
our support can change this in Live mode in the merchants configuration.
There is no way for you to change it directly. Contact support@heidelpay.com for further questions on this.
Yours,
Simon
